# Generated by Django 3.2.14 on 2023-03-01 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BillsAndSales', '0003_checkoutbill_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcalculations',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
