# Generated by Django 3.2.14 on 2023-03-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillsAndSales', '0005_billid_salebill'),
    ]

    operations = [
        migrations.AddField(
            model_name='billid',
            name='totalprice',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
