# Generated by Django 3.2.14 on 2023-03-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillsAndSales', '0006_billid_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billid',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
